import Link from "next/link";
import { Section } from "@/components/Section";
import { getAllAreas, getAllRoles } from "@/lib/content/load";

export default function Page(){
  const roles=getAllRoles(); const areas=getAllAreas();
  const by=(slug:string)=>roles.find(r=>r.slug===slug)!;
  return <>
    <section className="pageHero"><div className="container"><div className="eyebrow">Modelo de liderança</div><h1>Autonomia com accountability.</h1><p>Paulo lidera a empresa. Os Heads lideram suas áreas. Lucas aumenta a capacidade dos líderes. A estrutura só funciona se evitarmos bypasses e respeitarmos as alçadas.</p></div></section>
    <Section title="A cadeia executiva"><div className="leadershipArchitecture"><Link href="/papeis/ceo" className="leadershipCEO"><small>CEO</small><strong>Paulo</strong><span>Direção • prioridades • transformação • accountability</span></Link><div className="leadershipArrow">↓</div><div className="headGrid">{areas.map(a=><Link href={`/papeis/${a.leaderRole}`} className={`headCard ${a.id==="operacoes"?"accumulated":""}`} key={a.id}><small>HEAD</small><strong>{a.name}</strong><span>{a.id==="operacoes"?"Paulo acumula esta área":"Responde hierarquicamente ao CEO"}</span></Link>)}</div></div></Section>
    <Section eyebrow="Operações" title="Em Operações, a cadeia continua: Head → L3 → L4 → Squads"><div className="operationsDrilldown"><div><small>HEAD DE OPERAÇÕES</small><strong>Paulo</strong></div><span>↓</span><div><small>L3</small><strong>Ricardo + Alberto</strong><p>Lideram vários L4 e conjuntos de squads.</p></div><span>↓</span><div><small>L4</small><strong>Líderes de squads específicos</strong></div><span>↓</span><div><small>EXECUÇÃO</small><strong>Squads</strong></div></div><div className="callout compact"><strong>Sem bypass recorrente.</strong><p>O CEO reduz a interação operacional direta com L4 para fortalecer L3 como camada real de liderança.</p></div></Section>
    <Section eyebrow="Apoio transversal" title="Lucas exerce dois papéis diferentes"><div className="dualHat"><div className="card"><div className="cardKicker">Papel 1 — Governança</div><h3>Lucas como Sócio</h3><p>Participa do Conselho Estratégico e ajuda a orientar, tensionar e acompanhar a direção da empresa.</p><Link className="textLink" href="/governanca">Ver governança →</Link></div><div className="card mentor"><div className="cardKicker">Papel 2 — Organização</div><h3>{by("lucas").title}</h3><p>{by("lucas").mission}</p><blockquote>{by("lucas").missionHighlight}</blockquote><Link className="textLink" href="/papeis/lucas">Ver Role Chart →</Link></div></div><div className="authorityRule"><strong>Pessoa ≠ papel.</strong><p>A mesma pessoa pode exercer papéis diferentes sem misturar suas autoridades. Como mentor, Lucas apoia e provoca; não se torna chefe dos Heads.</p></div></Section>
  </>
}
